matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js: '10.5'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true
  - os: linux
    services: docker
    language: generic
    env:
    - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
    export PATH="/tmp/git-lfs:$PATH"
  fi
before_script:
- git lfs pull
script:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker run --rm \
      --env-file <(env) \
      -v ${PWD}:/project \
      -v ~/.cache/electron:/root/.cache/electron \
      -v ~/.cache/electron-builder:/root/.cache/electron-builder \
      electronuserland/builder:wine \
      /bin/bash -c "node -v && npm ci && npm run travislinux"
  else
    npm run travisdarwin
  fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine

deploy:
  provider: releases
  api_key:
    secure: ###
  file:
    - dist/*.yml
    - dist/*.dmg
    - dist/*.AppImage
    - dist/*.blockmap
    - dist/*.exe
  file_glob: true
  overwrite: true
  draft: true
  tag_name: $TRAVIS_TAG
  on:
    tags: true
